"""Caching utilities for featurization results."""

import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from loguru import logger


def _get_cache_dir() -> Path:
    """
    Get the cache directory for featurization results.

    Returns
    -------
    Path
        Path to the cache directory (~/.cache/openadmet-models/)

    """
    cache_dir = Path.home() / ".cache" / "openadmet-models"
    cache_dir.mkdir(parents=True, exist_ok=True)
    return cache_dir


def _hash_dataframe(df: pd.DataFrame) -> str:
    """
    Generate a hash of a pandas DataFrame.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame to hash

    Returns
    -------
    str
        SHA256 hash of the DataFrame

    """
    # Use pandas native hashing for better performance and memory usage
    hashed_values = pd.util.hash_pandas_object(df, index=True)
    return hashlib.sha256(hashed_values.values.tobytes()).hexdigest()


def _hash_params(params: dict[str, Any]) -> str:
    """
    Generate a hash of featurization parameters.

    Parameters
    ----------
    params : dict[str, Any]
        Dictionary of parameters to hash

    Returns
    -------
    str
        SHA256 hash of the parameters

    """
    # Convert params to sorted JSON string for consistent hashing
    params_json = json.dumps(params, sort_keys=True, default=str)
    return hashlib.sha256(params_json.encode()).hexdigest()


def generate_cache_key(
    data: pd.DataFrame | pd.Series,
    featurizer_type: str,
    featurizer_params: dict[str, Any],
) -> str:
    """
    Generate a cache key for featurization results.

    The cache key is based on:
    - Hash of the input data (DataFrame or Series)
    - Featurizer type
    - Featurizer parameters

    Parameters
    ----------
    data : pd.DataFrame | pd.Series
        Input data to featurize
    featurizer_type : str
        Type of featurizer (e.g., "FingerprintFeaturizer")
    featurizer_params : dict[str, Any]
        Parameters used for featurization

    Returns
    -------
    str
        Cache key (filename without extension)

    """
    # Convert Series to DataFrame for consistent handling
    if isinstance(data, pd.Series):
        data = data.to_frame()

    # Hash the data
    data_hash = _hash_dataframe(data)

    # Hash the featurizer params
    params_hash = _hash_params(featurizer_params)

    # Combine into a cache key
    cache_key = f"{featurizer_type}_{data_hash[:16]}_{params_hash[:16]}"
    return cache_key


def save_features_to_cache(
    cache_key: str, features: np.ndarray, indices: np.ndarray
) -> Path:
    """
    Save featurization results to cache using compressed NumPy format.

    Uses np.savez_compressed for fast I/O and efficient storage.

    Parameters
    ----------
    cache_key : str
        Cache key generated by generate_cache_key
    features : np.ndarray
        Featurized data
    indices : np.ndarray
        Indices of successfully featurized samples

    Returns
    -------
    Path
        Path to the cached file

    """
    cache_dir = _get_cache_dir()
    cache_path = cache_dir / f"{cache_key}.npz"

    # Save features and indices using compressed NumPy format
    # This is much faster than pickle for numerical arrays
    np.savez_compressed(cache_path, features=features, indices=indices)

    logger.info(
        f"Saved features to cache: {cache_path.name} "
        f"(shape: {features.shape}, {len(indices)} samples)"
    )

    return cache_path


def load_features_from_cache(
    cache_key: str,
) -> tuple[np.ndarray, np.ndarray] | None:
    """
    Load featurization results from cache using compressed NumPy format.

    Falls back to legacy .pkl format for backward compatibility.

    Parameters
    ----------
    cache_key : str
        Cache key generated by generate_cache_key

    Returns
    -------
    tuple[np.ndarray, np.ndarray] | None
        Tuple of (features, indices) if cache exists, None otherwise

    """
    cache_dir = _get_cache_dir()
    cache_path_npz = cache_dir / f"{cache_key}.npz"
    cache_path_pkl = cache_dir / f"{cache_key}.pkl"

    # Try new .npz format first (much faster)
    if cache_path_npz.exists():
        try:
            cache_data = np.load(cache_path_npz)
            features = cache_data["features"]
            indices = cache_data["indices"]
            logger.info(
                f"Loaded features from cache: {cache_path_npz.name} "
                f"(shape: {features.shape}, {len(indices)} samples)"
            )
            return features, indices
        except Exception as e:
            logger.warning(f"Failed to load cache from {cache_path_npz.name}: {e}")
            return None

    # Fall back to legacy .pkl format for backward compatibility
    if cache_path_pkl.exists():
        try:
            import joblib  # noqa: PLC0415

            cache_data = joblib.load(cache_path_pkl)
            features = cache_data["features"]
            indices = cache_data["indices"]
            logger.info(
                f"Loaded features from legacy cache: {cache_path_pkl.name} "
                f"(shape: {features.shape}, {len(indices)} samples)"
            )

            # Migrate to new format for future use
            logger.info("Migrating legacy cache to npz format...")
            save_features_to_cache(cache_key, features, indices)

            return features, indices
        except Exception as e:
            logger.warning(
                f"Failed to load legacy cache from {cache_path_pkl.name}: {e}"
            )
            return None

    logger.debug(f"Cache miss: {cache_key}")
    return None


def clear_cache(max_age_days: int | None = None) -> int:
    """
    Clear the featurization cache.

    Removes both .npz and .pkl cache files.

    Parameters
    ----------
    max_age_days : int | None
        If specified, only remove cache files older than this many days.
        If None, remove all cache files.

    Returns
    -------
    int
        Number of files removed

    """
    import time

    cache_dir = _get_cache_dir()
    removed_count = 0

    if not cache_dir.exists():
        return 0

    # Handle both .npz (new) and .pkl (legacy) formats
    for pattern in ["*.npz", "*.pkl"]:
        for cache_file in cache_dir.glob(pattern):
            should_remove = False

            if max_age_days is None:
                should_remove = True
            else:
                # Check file age
                file_age_seconds = time.time() - cache_file.stat().st_mtime
                file_age_days = file_age_seconds / (24 * 3600)
                if file_age_days > max_age_days:
                    should_remove = True

            if should_remove:
                try:
                    cache_file.unlink()
                    removed_count += 1
                    logger.debug(f"Removed cache file: {cache_file}")
                except Exception as e:
                    logger.warning(f"Failed to remove cache file {cache_file}: {e}")

    logger.info(f"Removed {removed_count} cache files")
    return removed_count
